version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    privileged: true
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "wuxiaochen0304"
      MYSQL_USER: "wuxc"
      MYSQL_PASS: "wuxiaochen0304"
      TZ: Asia/Shanghai
    command:
      --wait_timeout=31536000
      --interactive_timeout=31536000
      --max_connections=1000
      --default-authentication-plugin=mysql_native_password
    volumes:
      #映射mysql的数据目录到宿主机，保存数据
      - "/app/data/mysql:/var/lib/mysql"
      - "/app/services/mysql/my.cnf:/etc/mysql/my.cnf"
  wiblog:
    image: iwuxc/wiblog:latest
    container_name: wiblog
    volumes:
      - /app/webroot/wiblog/conf:/app/conf
    links:
      - mysql
    environment:
      - GODEBUG=netdns=cgo
      - RUN_MODE=prod
    ports:
      - "9000:9000"
    restart: always
  nginx:
    image: nginx:1.18
    container_name: nginx-1.18
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - wiblog
    volumes:
      - "/app/services/nginx/conf.d:/etc/nginx/conf.d/:rw"
      - "/app/services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/app/logs/nginx:/var/log/nginx/:rw"
