appname: wiblog
database:
  driver: mysql
  source: root:root@tcp(127.0.0.1:3306)/wiblog?charset=utf8mb4&parseTime=True&loc=Local
eshost:
eiblogapp:
  mode:
    name: cmd-wiblog
    enablehttp: true
    httpport: 9000
    host: example.com
  staticversion: 1 # 静态文件版本
  hotwords: # 热搜词
    - docker
    - mongodb
    - curl
    - dns
  general: # 常规配置
    pagenum: 10 # 首页展示文章数量
    pagesize: 20 # 管理界面
    startid: 11 # 起始ID，预留id不时之需, 不用管
    descprefix: "Desc:" # 文章描述前缀
    identifier: <!--more--> # 截取预览标识
    length: 400 # 自动截取预览, 字符数
    timezone: Asia/Shanghai # 时区
  disqus: # 评论相关
    shortname: xxxxxx
    publickey: wdSgxRm9rdGAlLKFcFdToBe3GT4SibmV7Y8EjJQ0r4GWXeKtxpopMAeIeoI2dTEg
    accesstoken: 50023908f39f4607957e909b495326af
  google: # 谷歌分析
    url: https://www.google-analytics.com/collect
    tid: UA-xxxxxx-1
    v: "1"
    t: pageview
    adsense: <script data-ad-client="ca-pub-5384494508691406" async src=""></script>
  qiniu: # 七牛OSS
    bucket: eiblog
    domain: st.deepzz.com
    accesskey: MB6AXl_Sj_mmFsL-Lt59Dml2Vmy2o8XMmiCbbSeC
    secretkey: BIrMy0fsZ0_SHNceNXk3eDuo7WmVYzj2-zrmd5Tf
  twitter: # twitter card
    card: summary
    site: deepzz02
    image: st.deepzz.com/static/img/avatar.jpg
    address: twitter.com/deepzz02
  feedrpc: # rss ping
    feedrurl: https://deepzz.superfeedr.com/
    pingrpc:
      - http://ping.baidu.com/ping/RPC2
      - http://rpc.pingomatic.com/
  # 数据初始化操作，可到博客后台修改
  account:
    username: deepzz # *后台登录用户名
    password: deepzz # *登录明文密码
backupapp:
  mode:
    name: cmd-backup
    enablehttp: true
    httpport: 9001
  backupto: qiniu # 备份到七牛云
  interval: 7d # 多久备份一次
  validity: 60d # 保存时长
  qiniu: # 七牛OSS
    bucket: backup
    domain: st.deepzz.com
    accesskey: MB6AXl_Sj_mmFsL-Lt59Dml2Vmy2o8XMmiCbbSeC
    secretkey: BIrMy0fsZ0_SHNceNXk3eDuo7WmVYzj2-zrmd5Tf
