name: WiblogCI

on:
  push:
    branches:
      - '*'

jobs:

  wiblog:

    name: Test with go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment:
      name: wiblog

    strategy:
      matrix:
        go_version: [ 1.17 ]
        os: [ ubuntu-latest ]

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run go modules tidy
        run: |
          go mod tidy
